// JS core for VibePlan
const STORAGE_KEY='vibeplan_data';const SETTINGS_KEY='vibeplan_cfg';let CONFIG={owner:'',repo:'',path:'data.json',token:''};let state={meta:{generated:new Date().toISOString()},items:[]};function $(id){return document.getElementById(id);}function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}function loadLocal(){const raw=localStorage.getItem(STORAGE_KEY);if(raw)state=JSON.parse(raw);}function saveCfg(){CONFIG.owner=$('inpOwner').value;CONFIG.repo=$('inpRepo').value;CONFIG.path=$('inpPath').value;CONFIG.token=$('inpToken').value;localStorage.setItem(SETTINGS_KEY,JSON.stringify(CONFIG));}
function loadCfg(){const s=localStorage.getItem(SETTINGS_KEY);if(s){CONFIG=JSON.parse(s);$('inpOwner').value=CONFIG.owner;$('inpRepo').value=CONFIG.repo;$('inpPath').value=CONFIG.path;$('inpToken').value=CONFIG.token;}}
function updateStatus(t){$('syncStatus').textContent='Статус: '+t;}
function render(){const week=$('weekGrid');week.innerHTML='';const days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];days.forEach(d=>{const col=document.createElement('div');col.className='card';const title=document.createElement('h4');title.textContent=d;col.appendChild(title);const ideas=state.items.filter(x=>x.day===d);if(ideas.length===0){const p=document.createElement('p');p.textContent='Нет идей';col.appendChild(p);}else{ideas.forEach((p,i)=>{const div=document.createElement('div');div.innerHTML=`<strong>${p.title}</strong><br>ES: ${p.es||''}<br>EN: ${p.en||''}`;const actions=document.createElement('div');actions.className='idea-actions';['tiktok','instagram','redbubble'].forEach(plat=>{const l=document.createElement('label');l.innerHTML=`<input type='checkbox' data-day='${p.day}' data-title='${p.title}' data-plat='${plat}' ${p.platforms[plat]?'checked':''}/> ${plat}`;actions.appendChild(l);});div.appendChild(actions);col.appendChild(div);});}week.appendChild(col);});document.querySelectorAll('input[type=checkbox]').forEach(cb=>{cb.onchange=e=>{const t=e.target.dataset.title;const d=e.target.dataset.day;const plat=e.target.dataset.plat;const item=state.items.find(x=>x.day===d&&x.title===t);if(item){item.platforms[plat]=e.target.checked;saveLocal();updateStatus('Изменения сохранены');}});});}
function addNew(){showModal('newModal');$('ideaDay').value='Пн';$('ideaCategory').value='';$('ideaTitle').value='';$('ideaTextES').value='';$('ideaTextEN').value='';$('platTik').checked=true;$('platIG').checked=true;$('platRB').checked=false;}
function saveIdea(){const day=$('ideaDay').value;const category=$('ideaCategory').value;const title=$('ideaTitle').value;const es=$('ideaTextES').value;const en=$('ideaTextEN').value;const plats={tiktok:$('platTik').checked,instagram:$('platIG').checked,redbubble:$('platRB').checked};state.items.push({day,category,title,es,en,platforms:plats,published:false});saveLocal();hideModal('newModal');render();updateStatus('Идея добавлена');}
function showModal(id){$(id).style.display='flex';}
function hideModal(id){$(id).style.display='none';}
async function syncToGitHub(){if(!CONFIG.token){alert('Укажите токен в настройках');return;}updateStatus('Синхронизация...');const json=JSON.stringify(state,null,2);const content=btoa(unescape(encodeURIComponent(json)));const api=`https://api.github.com/repos/${CONFIG.owner}/${CONFIG.repo}/contents/${CONFIG.path}`;let sha=null;const g=await fetch(api,{headers:{Authorization:'token '+CONFIG.token}});if(g.ok){const gj=await g.json();sha=gj.sha;}const body={message:'VibePlan update',content,sha,committer:{name:CONFIG.owner||'user',email:CONFIG.owner+'@users.noreply.github.com'}};const res=await fetch(api,{method:'PUT',headers:{Authorization:'token '+CONFIG.token,'Content-Type':'application/json'},body:JSON.stringify(body)});if(res.ok)updateStatus('Синхронизация успешна');else updateStatus('Ошибка при синхронизации');}
async function loadFromGitHub(){if(!CONFIG.token){alert('Укажите токен в настройках');return;}updateStatus('Загрузка...');const api=`https://api.github.com/repos/${CONFIG.owner}/${CONFIG.repo}/contents/${CONFIG.path}`;const r=await fetch(api,{headers:{Authorization:'token '+CONFIG.token}});if(r.ok){const j=await r.json();const raw=decodeURIComponent(escape(atob(j.content)));state=JSON.parse(raw);saveLocal();render();updateStatus('Загружено с GitHub');}else updateStatus('Ошибка загрузки');}
function init(){loadCfg();loadLocal();render();$('btnNew').onclick=addNew;$('saveIdea').onclick=saveIdea;$('closeNew').onclick=()=>hideModal('newModal');$('btnSettings').onclick=()=>showModal('settingsModal');$('saveSettings').onclick=()=>{saveCfg();hideModal('settingsModal');};$('closeSettings').onclick=()=>hideModal('settingsModal');$('btnSync').onclick=syncToGitHub;$('btnLoad').onclick=loadFromGitHub;$('btnExport').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vibeplan.json';a.click();};updateStatus('Готово');}
document.addEventListener('DOMContentLoaded',init);